version: '3'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend-web

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production

  frontend-web:
    build:
      context: ./frontend-web
      dockerfile: Dockerfile

  # Vous pouvez ajouter d'autres services ici, comme MongoDB